version: 2.1

orbs:
  node: circleci/node@5
  docker: circleci/docker@2.4.0
  azure-aks: circleci/azure-aks@0.3.0
  kubernetes: circleci/kubernetes@1.3.1
  snyk: snyk/snyk@2.1.0
  sonarcloud: sonarsource/sonarcloud@2.0.0  # Add SonarCloud orb

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --passWithNoTests
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  snyk-scan:
    docker:
      - image: snyk/snyk:docker
    steps:
      - checkout
      - run:
          name: Authenticate Snyk
          command: snyk auth $SNYK_TOKEN
      - run:
          name: Run Snyk test
          command: snyk test --fail-on=upgradable
    environment:
      SNYK_TOKEN: "74eee921-3efe-4488-adce-fe1d7b21a00b"
  docker-config:
    docker:
      - image: cimg/node:21.7.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_LOGIN/$APP_NAME:latest .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$APP_NAME:latest
  bump-docker-tag-kustomize:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Install kustomize
          command: |
            URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.5.2/kustomize_v4.5.2_linux_amd64.tar.gz
            curl -L $URL | tar zx
            [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
            $SUDO chmod +x ./kustomize
            $SUDO mv ./kustomize /usr/local/bin
      - checkout
      - run:
          name: Bump Docker Tag
          command: |
            cd manifests
            kustomize edit set image $APP_NAME=$DOCKER_LOGIN/$APP_NAME:$CIRCLE_SHA1
            kustomize build . > $APP_NAME.yaml
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: Commit & Push to GitHub
          command: |
            git config user.email "$GITHUB_EMAIL"
            git config user.name "CircleCI User"
            git checkout $CIRCLE_BRANCH           
            git add manifests/$APP_NAME.yaml
            git add manifests/kustomization.yaml
            git commit -am "Bumps docker tag [skip ci]"
            git push origin $CIRCLE_BRANCH
  aks-deploy:
    docker:
      - image: cimg/base:current
    parameters:
      cluster-name:
        description: Name of the AKS cluster.
        type: string
      resource-group:
        description: Resource group that the cluster is in
        type: string
    steps:
      - checkout
      - run:
          name: Pull Updated code from repos
          command: git pull origin $CIRCLE_BRANCH
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          perform-login: true
          resource-group: << parameters.resource-group >>
      - kubernetes/create-or-update-resource:
          resource-file-path: manifests/$APP_NAME.yaml
          resource-name: kustomization/$APP_NAME
  sonarcloud-scan:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: SonarCloud Scan
          command: sonar-scanner \
            -Dsonar.projectKey="SandervanDeurzenStudent_WanderQuest-frontend" \
            -Dsonar.organization="sandervandeurzenstudent" \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login="560f6e98b54d53caa92d22cf952c6080231af154"

workflows:
  build-and-test:
    jobs:
      - test-node
      - snyk-scan
      - sonarcloud-scan:
          requires:
            - snyk-scan
      - build-node:
          requires:
            - test-node
            - snyk-scan
      - docker-config:
          requires:
            - build-node
          context:
            - wanderquest
      - bump-docker-tag-kustomize:
          requires:
            - docker-config
      - aks-deploy:
          cluster-name: $CLUSTER_NAME
          resource-group: $RESOURCE_GROUP
          requires:
            - bump-docker-tag-kustomize
          context:
            - wanderquest
