apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: wanderquest-frontend
images:
- newName: /
  newTag: 9269536029565b6a62130445a3f926e62e627e80
- name: wanderquest-frontend-aks-app
  newName: sandervandeurzen/wanderquest-frontend-aks-app
  newTag: 7da4c40d74c000b483510019e7a3b3b030ecbd0f
