apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: wanderquest-frontend
images:
- newName: /
  newTag: 9269536029565b6a62130445a3f926e62e627e80
- name: wanderquest-frontend-aks-app
  newName: /wanderquest-frontend-aks-app
  newTag: bfa48c3ba341aa4e0d7b313931d4cb1e25d67305
