apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: wanderquest-frontend
images:
- newName: /
  newTag: 9269536029565b6a62130445a3f926e62e627e80
- name: wanderquest-frontend-aks-app
  newName: /wanderquest-frontend-aks-app
  newTag: b9800de38c97494d9d5d503222d87c33e82657b5
