apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: wanderquest-frontend
images:
- newName: /
  newTag: 73646cb45996b7dc63ab2e13643a1ff3054c2061
- name: wanderquest-frontend-aks-app
  newName: sandervandeurzen/wanderquest-frontend-aks-app
  newTag: 7da4c40d74c000b483510019e7a3b3b030ecbd0f
