apiVersion: v1
kind: Service
metadata:
  name: wanderquest-frontend
spec:
  selector:
    app: wanderquest-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

