apiVersion: v1
kind: Service
metadata:
  name: wanderquest-frontend
spec:
  selector:
    app: wanderquest-frontend
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 1000
  type: LoadBalancer
